% GSA code v1.1.
% Generated by Esmat Rashedi, 2010. 
% "	E. Rashedi, H. Nezamabadi-pour and S. Saryazdi,
%“GSA: A Gravitational Search Algorithm”, Information sciences, vol. 179,
%no. 13, pp. 2232-2248, 2009."
%
% This function gives boundaries and dimension of search space for test functions.
function [down,up,dim]=test_functions_range(F_index)

%If lower bounds of dimensions are the same, then 'down' is a value.
%Otherwise, 'down' is a vector that shows the lower bound of each dimension.
%This is also true for upper bounds of dimensions.

%Insert your own boundaries with a new F_index.

dim=3;
if F_index==1
    down=-100;up=100;
end

if F_index==2
    down=-10;up=10;
end

if F_index==3
    down=-100;up=100;
end

if F_index==4
    down=-100;up=100;
end

if F_index==5
      down=-1;up=1;
%     down=-30;up=30;
end

if F_index==6
    down=-100;up=100;
end
%modif
if F_index==7
    down=1;up=255;
end

if F_index==8
    down=-500;up=500;
end

if F_index==9
    down=-5.12;up=5.12;
end

if F_index==10
    down=-32;up=32;
end

if F_index==11
    down=-600;up=600;
end

if F_index==12
    down=-50;up=50;
end

if F_index==13
    down=-50;up=50;
end

if F_index==14
    down=-5;up=5;
end

%Hybrid
if F_index==15
    down=-100;up=100;
end

if F_index==16
    down=-100;up=100;
end


if F_index==17
    down=-100;up=100;

end


if F_index==18
    down=-100;up=100;

end


if F_index==19
    down=-100;up=100;

end

if F_index==20
    down=-100;up=100;

end






 
 
